In [ ]:
#from google.colab import files
#uploaded = files.upload()

In [ ]:
#!unzip data.zip

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from sklearn.model_selection import train_test_split
import json
import glob
import random
import collections
from glob import glob
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

from skimage.io import imread
from skimage.transform import resize
from keras import layers
from keras import models
import keras
from keras.layers import LeakyReLU
from keras.models import Sequential, Model, load_model
from keras.layers import Input, Conv1D, Conv2D, MaxPooling1D, MaxPooling2D, Dense, Dropout, Activation, Flatten
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import seaborn as sns
import shutil
import keras
from PIL import Image

In [2]:
from glob import glob
trn1='D:/Inv_Data_Imbalance/data/invasive-aquatic-species-data/invasive/*/'
trn2='D:/Inv_Data_Imbalance/data/invasive-aquatic-species-data/noninvasive/*/'
tr1= glob(trn1)
tr2= glob(trn2)

In [15]:
imgs = glob(tr1[9]+'/*')
len(tr2)

3700

In [3]:
tr1= shuffle(tr1)
tr2= shuffle(tr2)

In [4]:
tran_index_inv = np.round( len(tr1)* .8  )
tran_index_noninv = np.round( len(tr2)* .8  )
tran_index_noninv

2960.0

In [5]:
from keras.models import load_model
from keras.callbacks import Callback,ModelCheckpoint
from keras.models import Sequential,load_model
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
import keras.backend as K
import numpy as np
import pandas as pd

from skimage.io import imread
from skimage.transform import resize
from keras import layers
from keras import models
import keras
from keras.layers import LeakyReLU
from keras.models import Sequential, Model, load_model
from keras.layers import Input, Conv1D,Reshape, Conv2D, MaxPooling1D, MaxPooling2D, Dense, Dropout, Activation, Flatten, UpSampling2D
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


model = load_model('encoder80.h5')
encoder = Model(inputs=model.input, outputs=model.get_layer('encoder').output)

In [6]:
data = []
label = []
breath = []
total = 0

for j in tr1[:(int) (tran_index_inv)]:
    label.append(1)
    a = glob(j+'/*')
    breath.append(len(a))
    total = total + len(a)
    
for j in tr2[:(int) (tran_index_noninv)]:
    label.append(0)
    a = glob(j+'/*')
    breath.append(len(a)) 
    total = total + len(a)

for j in range(0,len(tr1[:(int) (tran_index_inv)])):
    a = glob(tr1[j]+'/*')
    for k in range(0,len(a)):
        data.append(a[k])

for j in range(0,len(tr2[:(int) (tran_index_noninv)])):
    a = glob(tr2[j]+'/*')
    for k in range(0,len(a)):
        data.append(a[k])        
        

imgdata=[]
for i in range(len(data)):
    a = Image.open(data[i])
    b = a.resize((40, 40))
    c = np.array(b)
    imgdata.append(c.reshape(40,40,3))
    
from tensorflow.keras.utils import to_categorical
idata = np.array(imgdata)
X_train = idata
X_train = X_train.astype('float32') / 255.
X_train = np.reshape(X_train, (len(X_train),40,40,3))

encoded = encoder.predict(X_train)

encoded[5]

array([ 9.6086711e-03, -9.3669966e-02, -9.6447907e-02, -8.6818703e-02,
        7.7567406e-02,  1.9020731e-02,  4.0794928e-02,  6.2635168e-05,
       -4.6611305e-02, -4.7604204e-04, -7.5581715e-02,  5.7421941e-02,
        6.9124638e-03, -4.2364165e-02, -1.6146716e-01, -1.9400319e-01,
        1.2882081e-01,  9.8593816e-02,  6.6207349e-02, -6.4897155e-03,
        2.8586350e-02,  1.3940273e-02, -9.0845659e-02, -4.1631501e-02,
        2.3579005e-02,  5.7420217e-02, -1.0428248e-01, -2.1749079e-02,
        2.9841663e-02, -4.4662822e-02, -1.2994805e-01,  2.6749004e-02,
       -3.5418514e-03, -3.8465835e-02,  3.9044306e-02,  4.4700086e-02,
        1.5987540e-03, -6.3281797e-02, -1.3490459e-01, -3.5610344e-02,
       -1.8756554e-01, -7.6036854e-03,  5.1221952e-02, -9.9714920e-02,
       -7.2538897e-02,  3.8552828e-02,  4.0632445e-02, -6.4132117e-02,
        2.6336871e-02,  2.7594235e-02, -5.8440180e-03, -4.5225449e-02,
        7.1946792e-02,  3.1144006e-02,  3.8435992e-02,  2.1447694e-01,
      

In [7]:
end= 0
train_df= []
for i in range(0, len(breath)):
    
    y = end+breath[i]
    en_sum = [sum(x) for x in zip(*encoded[end:y])]
    res = [(x/breath[i]) for x in (en_sum)]
    train_df.append(res)
    #print(en_sum)
    #print(res)
    end = end + breath[i]
        
Y_train =(label)
train_df = np.array(train_df)
train_df,Y_train = shuffle(train_df,Y_train)
np.shape(train_df)

(3499, 100)

In [52]:
np.shape(train_df)

(3499, 48)

In [8]:
data = []
label = []
breath = []
total = 0

for j in tr1[(int) (tran_index_inv) + 1 :]:
    label.append(1)
    a = glob(j+'/*')
    breath.append(len(a))
    total = total + len(a)
    
for j in tr2[ (int)(tran_index_noninv) + 1:]:
    label.append(0)
    a = glob(j+'/*')
    breath.append(len(a)) 
    total = total + len(a)

for j in range(0,len(tr1[(int) (tran_index_inv) + 1 :])):
    a = glob(tr1[j]+'/*')
    for k in range(0,len(a)):
        data.append(a[k])

for j in range(0,len(tr2[ (int)(tran_index_noninv) + 1:])):
    a = glob(tr2[j]+'/*')
    for k in range(0,len(a)):
        data.append(a[k])        
        

imgdata=[]
for i in range(len(data)):
    a = Image.open(data[i])
    b = a.resize((40, 40))
    c = np.array(b)
    imgdata.append(c.reshape(40,40,3))
    
from tensorflow.keras.utils import to_categorical
idata = np.array(imgdata)
X_test = idata
X_test = X_test.astype('float32') / 255.
X_test = np.reshape(X_test, (len(X_test),40,40,3))

encoded = encoder.predict(X_test)

encoded[5]

array([ 9.6086711e-03, -9.3669966e-02, -9.6447907e-02, -8.6818703e-02,
        7.7567406e-02,  1.9020731e-02,  4.0794928e-02,  6.2635168e-05,
       -4.6611305e-02, -4.7604204e-04, -7.5581715e-02,  5.7421941e-02,
        6.9124638e-03, -4.2364165e-02, -1.6146716e-01, -1.9400319e-01,
        1.2882081e-01,  9.8593816e-02,  6.6207349e-02, -6.4897155e-03,
        2.8586350e-02,  1.3940273e-02, -9.0845659e-02, -4.1631501e-02,
        2.3579005e-02,  5.7420217e-02, -1.0428248e-01, -2.1749079e-02,
        2.9841663e-02, -4.4662822e-02, -1.2994805e-01,  2.6749004e-02,
       -3.5418514e-03, -3.8465835e-02,  3.9044306e-02,  4.4700086e-02,
        1.5987540e-03, -6.3281797e-02, -1.3490459e-01, -3.5610344e-02,
       -1.8756554e-01, -7.6036854e-03,  5.1221952e-02, -9.9714920e-02,
       -7.2538897e-02,  3.8552828e-02,  4.0632445e-02, -6.4132117e-02,
        2.6336871e-02,  2.7594235e-02, -5.8440180e-03, -4.5225449e-02,
        7.1946792e-02,  3.1144006e-02,  3.8435992e-02,  2.1447694e-01,
      

In [70]:
np.shape(encoded)

(22531, 64)

In [9]:
end= 0
test_df= []
for i in range(0, len(breath[:850])):
    
    y = end+breath[i]
    en_sum = [sum(x) for x in zip(*encoded[end:y])]
    #len()
    res = [(x/breath[i]) for x in (en_sum)]
    test_df.append(res)
    #print(en_sum)
    #print(res)
    end = end + breath[i]
        
Y_test = (label)
test_df = np.array(test_df)
test_df,Y_test = shuffle(test_df,Y_test[:850])
np.shape(test_df)

(850, 100)

In [10]:
import numpy as np
import pandas as pd

from skimage.io import imread
from skimage.transform import resize
from keras import layers
from keras import models
import keras
from keras.layers import LeakyReLU
from keras.models import Sequential, Model, load_model
from keras.layers import Input, Conv1D, Conv2D, MaxPooling1D, MaxPooling2D, Dense, Dropout, Activation, Flatten
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from keras.callbacks import Callback,ModelCheckpoint
from keras.models import Sequential,load_model
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
import keras.backend as K

def get_f1(y_true, y_pred): #taken from old keras source code
    tp = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    
    tn = K.sum(K.round(K.clip((1-y_true) * (1-y_pred), 0, 1)))
    fp = K.sum(K.round(K.clip((1-y_true) * (y_pred), 0, 1)))
    fn = K.sum(K.round(K.clip((y_true) * (1-y_pred), 0, 1)))
    

    f1_val = tp / ( tp + ( (1/2) * (fp+fn) ) + K.epsilon())
    return f1_val

In [29]:

model = models.Sequential()
model.add(layers.Dense(30, activation="relu", input_shape=(50,)))
model.add(layers.Dense(16, activation="relu"))
model.add(layers.Dense(2, activation="softmax"))


In [ ]:

model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=([get_f1]))

model.fit(selected_features_train, Y_train, epochs=300, batch_size=32, validation_split = .3, verbose = 1)

Epoch 1/300
77/77 [==============================] - 4s 20ms/step - loss: 0.0530 - get_f1: 0.9793 - val_loss: 0.0858 - val_get_f1: 0.9697
Epoch 2/300
77/77 [==============================] - 1s 9ms/step - loss: 0.0499 - get_f1: 0.9797 - val_loss: 0.0872 - val_get_f1: 0.9669
Epoch 3/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0503 - get_f1: 0.9793 - val_loss: 0.0854 - val_get_f1: 0.9688
Epoch 4/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0487 - get_f1: 0.9806 - val_loss: 0.0870 - val_get_f1: 0.9688
Epoch 5/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0470 - get_f1: 0.9825 - val_loss: 0.0869 - val_get_f1: 0.9706
Epoch 6/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0476 - get_f1: 0.9810 - val_loss: 0.0859 - val_get_f1: 0.9678
Epoch 7/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0456 - get_f1: 0.9830 - val_loss: 0.0866 - val_get_f1: 0.9659
Epoch 8/300
77/77 [=====================

77/77 [==============================] - 1s 9ms/step - loss: 0.0223 - get_f1: 0.9927 - val_loss: 0.1015 - val_get_f1: 0.9735
Epoch 61/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0198 - get_f1: 0.9927 - val_loss: 0.1004 - val_get_f1: 0.9735
Epoch 62/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0209 - get_f1: 0.9935 - val_loss: 0.1072 - val_get_f1: 0.9678
Epoch 63/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0183 - get_f1: 0.9940 - val_loss: 0.1067 - val_get_f1: 0.9697
Epoch 64/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0192 - get_f1: 0.9951 - val_loss: 0.1101 - val_get_f1: 0.9688
Epoch 65/300
77/77 [==============================] - 1s 8ms/step - loss: 0.0189 - get_f1: 0.9939 - val_loss: 0.1089 - val_get_f1: 0.9697
Epoch 66/300
77/77 [==============================] - 1s 9ms/step - loss: 0.0186 - get_f1: 0.9931 - val_loss: 0.1056 - val_get_f1: 0.9725
Epoch 67/300
77/77 [===========================

77/77 [==============================] - 1s 7ms/step - loss: 0.0076 - get_f1: 0.9984 - val_loss: 0.1428 - val_get_f1: 0.9744
Epoch 120/300
77/77 [==============================] - 1s 7ms/step - loss: 0.0073 - get_f1: 0.9992 - val_loss: 0.1449 - val_get_f1: 0.9688
Epoch 121/300
77/77 [==============================] - 1s 7ms/step - loss: 0.0078 - get_f1: 0.9980 - val_loss: 0.1424 - val_get_f1: 0.9725
Epoch 122/300
77/77 [==============================] - 1s 7ms/step - loss: 0.0072 - get_f1: 0.9980 - val_loss: 0.1418 - val_get_f1: 0.9773
Epoch 123/300
77/77 [==============================] - 1s 7ms/step - loss: 0.0072 - get_f1: 0.9980 - val_loss: 0.1413 - val_get_f1: 0.9688
Epoch 124/300
77/77 [==============================] - 1s 7ms/step - loss: 0.0078 - get_f1: 0.9980 - val_loss: 0.1430 - val_get_f1: 0.9754
Epoch 125/300
77/77 [==============================] - 1s 7ms/step - loss: 0.0062 - get_f1: 0.9988 - val_loss: 0.1518 - val_get_f1: 0.9735
Epoch 126/300
77/77 [====================

In [32]:
Y_test = Y_test
pred = model.predict(selected_features_test)
p = np.round(pred)
f1 = get_f1(Y_test, p)
f1

y_p = []
for i in range(len(p)):
    if ( p[i][0] == 0 ):
        y_p.append(1)
    else :
        y_p.append(0)
y_p = np.array(y_p)
y_t = []
for i in range(len(Y_test)):
    if ( Y_test[i][0] == 0 ):
        y_t.append(1)
    else :
        y_t.append(0)
y_t = np.array(y_t)

from sklearn.metrics import confusion_matrix
a=(confusion_matrix(y_t, y_p , labels=[0,1]))
a.T

array([[711,   7],
       [  5, 127]], dtype=int64)

In [90]:
np.shape(selected_features_test)

(850, 30)

In [100]:
pred = model.predict(selected_features_test)
np.shape(pred)

(850, 2)

In [ ]:
from skfeature.utility import construct_W
kwargs_W = {"metric":"euclidean","neighbor_mode":"knn","weight_mode":"heat_kernel","k":5,'t':1}
W = construct_W.construct_W(X_train, **kwargs_W)



In [11]:
from skfeature.function.similarity_based import fisher_score
score = fisher_score.fisher_score(train_df, Y_train)
score

array([64, 84, 26,  5, 28, 93, 20, 45, 87, 73, 65, 68, 97, 24, 25, 71, 16,
       86, 42, 41, 59, 37, 99, 18, 57, 47, 51, 35, 82,  0, 53, 33, 50, 31,
        8, 94, 74, 30, 10, 36, 23, 34,  1,  6, 90,  9, 14, 81, 58, 11, 22,
       48, 88, 79, 55, 89, 46, 85, 70, 12, 17, 39, 80, 83, 62, 96, 56, 67,
       69, 27, 66, 91, 15, 60, 43, 92,  3,  2, 98, 77, 63, 49, 52, 75,  7,
       19, 13, 38, 72, 54, 21, 76, 95, 61, 29,  4, 32, 40, 78, 44])

In [12]:
idx = fisher_score.fisher_score(train_df, Y_train, mode='rank') #returns rank directly instead of fisher score. so no need for feature_ranking
print(idx)

[64 84 26  5 28 93 20 45 87 73 65 68 97 24 25 71 16 86 42 41 59 37 99 18
 57 47 51 35 82  0 53 33 50 31  8 94 74 30 10 36 23 34  1  6 90  9 14 81
 58 11 22 48 88 79 55 89 46 85 70 12 17 39 80 83 62 96 56 67 69 27 66 91
 15 60 43 92  3  2 98 77 63 49 52 75  7 19 13 38 72 54 21 76 95 61 29  4
 32 40 78 44]


In [13]:
num_fea = 50
selected_features_train = train_df[:, idx[0:num_fea]]
selected_features_test = test_df[:, idx[0:num_fea]]

In [14]:
selected_features_train = np.array(selected_features_train.astype('float32'))
selected_features_test = np.array(selected_features_test.astype('float32'))
Y_test = to_categorical(Y_test)
Y_train = to_categorical(Y_train)

In [63]:
selected_features_train[0]

array([ 0.00371764,  0.00498228,  0.05336196, -0.01909056, -0.00454004,
        0.01734734, -0.00291995, -0.09460013,  0.01814024, -0.00771649,
       -0.02187526, -0.03938345, -0.00258373, -0.00736343,  0.0619969 ,
        0.00981687, -0.02070476,  0.02501709,  0.01276932,  0.01795072,
        0.02019595,  0.01036787,  0.01084555, -0.02179153, -0.01408069,
        0.0213378 ,  0.00896297,  0.02400279,  0.05476911,  0.03921095],
      dtype=float32)

0

In [99]:
Y_test = to_categorical(Y_test)
np.shape(Y_test)

(850, 2)

0

In [112]:
np.shape(Y_test)

(850, 2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9315706>

0.9315706080411963

array([[15968,   776],
       [  606,  2846]], dtype=int64)

0.9344424638542286

0.829075064369182

<tf.Tensor: shape=(), dtype=float32, numpy=3.1974423e-14>